// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort():Promise<string>;

export function IsOnline():Promise<boolean>;

export function RemoveMP3(arg1:string):void;

export function SetKeys(arg1:any):void;

export function AddKey(arg1:string,arg2:string):void;

export function FilePrompt():Promise<string>;

export function GetKeys():Promise<any>;

export function RequestPath(arg1:string):void;

export function StartFile():void;
