// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartFile() {
  return window['go']['main']['App']['StartFile']();
}

export function AddKey(arg1, arg2) {
  return window['go']['main']['App']['AddKey'](arg1, arg2);
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function RemoveMP3(arg1) {
  return window['go']['main']['App']['RemoveMP3'](arg1);
}

export function RequestPath(arg1) {
  return window['go']['main']['App']['RequestPath'](arg1);
}

export function SetKeys(arg1) {
  return window['go']['main']['App']['SetKeys'](arg1);
}

export function FilePrompt() {
  return window['go']['main']['App']['FilePrompt']();
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}
