// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKey(arg1:string,arg2:string):Promise<void>;

export function FilePrompt():Promise<string>;

export function GetKeys():Promise<{[key: string]: string}>;

export function GetPort():Promise<string>;

export function IsOnline():Promise<boolean>;

export function NeedsUpdate():Promise<boolean>;

export function RemoveMP3(arg1:string):Promise<void>;

export function RequestPath(arg1:string):Promise<void>;

export function SetKeys(arg1:{[key: string]: string}):Promise<void>;

export function StartFile():Promise<boolean>;

export function Update():Promise<boolean>;
