// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['Config']['GetConfig']();
}

export function SetConfig(arg1) {
  window['go']['main']['Config']['SetConfig'](arg1);
}
